/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
<<<<<<< HEAD
 * Generated at: 2022-06-17 05:13:06 UTC
=======
 * Generated at: 2022-06-26 23:44:23 UTC
>>>>>>> NelsonCriollo
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Mantenimiento_005fDevolucion_005fde_005fBienes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Nelcriollo/Desktop/ProyectoFinal_LPII/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProyectoFinal_LPII/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098729090000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1653951253000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
<<<<<<< HEAD
=======
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
>>>>>>> NelsonCriollo

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
<<<<<<< HEAD
=======
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
>>>>>>> NelsonCriollo
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
<<<<<<< HEAD
=======
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
>>>>>>> NelsonCriollo
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;


if (request.getSession().getAttribute("LISTAMenu") == null)
	response.sendRedirect("login.jsp");

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Mantenimiento Devolucion</title>\r\n");
      out.write("\r\n");
      out.write("<!--  jquery-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\" https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css\">\r\n");
      out.write("\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.datatables.net/1.11.5/css/dataTables.bootstrap5.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write(".help-block {\r\n");
      out.write("    color: red;\r\n");
      out.write("}\r\n");
      out.write(".form-group.has-error .form-control-label {\r\n");
      out.write("\tcolor: red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-group.has-error .form-control {\r\n");
      out.write("\tborder: 1px solid red;\r\n");
      out.write("\tbox-shadow: 0 0 0 0.2rem rgba(250, 16, 0, 0.18);\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"mt-5 p-5 bg-light\">\r\n");
<<<<<<< HEAD
      out.write("<button type=\"button\" class=\"btn btn-dark\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Genera Ficha de Devolución</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-fullscreen\">\r\n");
=======
      out.write("<button type=\"button\" class=\"btn btn-dark btn-generaFichaDevol\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">Genera Ficha de Devolución</button>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-fullscreen modificarTamano\">\r\n");
>>>>>>> NelsonCriollo
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Mantenimiento de Devolución</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      \r\n");
<<<<<<< HEAD
      out.write("   <form id=\"IdRegistrarDevol\" method=\"post\" action=\"ServletBien?tipo=REGISTRAR\"  class=\"form-horizontal border mt-1 mb-3\">\r\n");
      out.write("\t<div class=\"row mx-3 my-1\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row mx-3 my-3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 text-center p-2 lh-sm\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h6 class=\"fw-bolder\">Registro de Devolución</h6>\r\n");
=======
      out.write("   <form id=\"IdRegistrarDevol\" method=\"post\" action=\"ServletDevolucionBien?tipo=REGISTRAR\"  class=\"form-horizontal border mt-1 mb-3\">\r\n");
      out.write("\t<div class=\"row mx-3 my-1\">\r\n");
      out.write("\t\t\t <input type=\"hidden\" class=\"form-control\" id=\"idIdentificador\" name=\"tipoOperacion\" value=\"0\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row mx-3 my-3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 text-center p-2 lh-sm\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h5 class=\"fw-bolder\">RUC:20401381291</h5>\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t<p>Av Abancay cuadra. 5 S/N, Lima,Perú</p>\r\n");
      out.write("\t\t\t\t\t<p>Telf: 990990215 - 989435229</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 text-center p-3 lh-sm border border-secondary\">\r\n");
<<<<<<< HEAD
      out.write("\t\t\t\t\t<h5 class=\"fw-bolder\">RUC:20401381291</h5>\r\n");
      out.write("\t\t\t\t\t<h7>Ficha de Devolución</h7>\r\n");
=======
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<h6 class=\"col-form-label fw-bolder\">Ficha de Devolución</h6>\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mb-2 row g-2 d-flex justify-content-center mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputPassword6\" class=\"col-form-label fw-bolder\">NRO:</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-auto\">\r\n");
<<<<<<< HEAD
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"idnumerodev\" name=\"numerodev\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"0\" class=\"form-control\"readonly=\"readonly\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-describedby=\"passwordHelpInline\">\r\n");
=======
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"idnumerodevol\" name=\"numerodevol\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control text-primary fw-bold text-center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-describedby=\"passwordHelpInline\" readonly=\"readonly\">\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\t</div>\r\n");
<<<<<<< HEAD
      out.write("\r\n");
      out.write("\t<div class=\"row px-3\">\r\n");
      out.write("\t\t<h5>Datos de Cabecera</h5>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"row p-3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-10 col-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\r\n");
=======
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row px-3\">\r\n");
      out.write("\t\t\t<div class=\"row p-3 border ms-0\">\r\n");
      out.write("\t\t\t<h5 class=\"text-info\">Datos de Cabecera</h5>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-12 col-12\">\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1 divCodigoDevolOculto\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"txtFechaDevolucion\" class=\" col-6 col-form-label\">Código de Devolución</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control text-success fw-bolder\" name=\"codigodevol\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"idcodigodevol\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"txtFechaDevolucion\" class=\" col-6 col-form-label\">Fecha\r\n");
      out.write("\t\t\t\t\t\t\t\t\tde Devolución</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\r\n");
<<<<<<< HEAD
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"date\" id=\"txtFechaDevolucion\" class=\"form-control\">\r\n");
=======
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"date\" id=\"idFechaDevolucion\" name=\"fech\" class=\"form-control\">\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"mpDepartamento\" class=\"col-6 col-form-label\">Remitente</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\r\n");
<<<<<<< HEAD
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"idRemitente\" name=\"remitente\" class=\"form-control\">\r\n");
=======
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"idRemitente\" name=\"remitente\" class=\"form-control\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.usuario.nombre}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.usuario.apellido}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\">\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"txtProveedor\" class=\" col-6 col-form-label\">Proveedor</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\r\n");
<<<<<<< HEAD
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"txtProveedor\" class=\"form-select\">\r\n");
=======
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"idProveedor\" name=\"proveedor\" class=\"form-select\">\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t\t\t\t\t\t<option selected>Seleccionar</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"mpDepartamento\" class=\"col-6 col-form-label\">Total\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcrédito adeudado</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\r\n");
<<<<<<< HEAD
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"mpDepartamento\" class=\"form-control\">\r\n");
=======
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"idtotalCreditoAdeudo\" name=\"totalCreditoAdeudo\" class=\"form-control text-danger fw-bold\" value=\"0\" readonly=\"readonly\">\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
<<<<<<< HEAD
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row p-3  mb-3\">\r\n");
      out.write("\t\t<h5 class=\"\">Datos del Detalle</h5>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  <div class=\"col-md-2\">\r\n");
      out.write("    <label for=\"validationDefault01\" class=\"form-label\">Nro Ficha</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"validationDefault01\" value=\"\" required>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"col-md-2\">\r\n");
      out.write("    <label for=\"validationDefault02\" class=\"form-label\">Código de Bien</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"idBien\" name=\"codBien\" value=\"\" required>\r\n");
      out.write("  </div>\r\n");
      out.write("    <div class=\"col-md-3\">\r\n");
      out.write("    <label for=\"validationDefault02\" class=\"form-label\">Nombre del Bien</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"idNomBien\" name=\"nomBien\" value=\"\" required>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"col-md-5\">\r\n");
      out.write("\t    <div class=\"form-floating\">\r\n");
      out.write("\t\t  <textarea class=\"form-control\" placeholder=\"\" id=\"idDescrip\" name=\"descripcionDano\" style=\"height: 100px\"></textarea>\r\n");
      out.write("\t\t  <label for=\"floatingTextarea2\">Descrpción del Daño</label>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <label for=\"validationDefaultUsername\" class=\"form-label\">Precio</label>\r\n");
      out.write("    <div class=\"input-group\">\r\n");
      out.write("      <span class=\"input-group-text\" id=\"inputGroupPrepend2\">S/.</span>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"idprecio\" name=\"precio\"  aria-describedby=\"inputGroupPrepend2\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write(" <div class=\"col-md-4\">\r\n");
      out.write("    <label for=\"validationDefault02\" class=\"form-label\">Cantidad</label>\r\n");
      out.write("    <input type=\"text\" class=\"form-control\" id=\"idcantidad\" name=\"cantidad\" value=\"\" required>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"col-md-4\">\r\n");
      out.write("    <label for=\"validationDefaultUsername\" class=\"form-label\">Crédito Adeudado</label>\r\n");
      out.write("    <div class=\"input-group\">\r\n");
      out.write("      <span class=\"input-group-text\" id=\"inputGroupPrepend2\">S/.</span>\r\n");
      out.write("      <input type=\"text\" class=\"form-control\" id=\"idcreditoAdeudado\" name=\"creditoAdeudado\"  aria-describedby=\"inputGroupPrepend2\" required>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"row mt-5 p-3\">\t\r\n");
      out.write("      \t\t<div class=\"col-lg-6 col-sm-12 mt-4 table-responsive\">\r\n");
      out.write("\t\t\t<table id=\"tableBienes\" class=\"table table-striped table-sm\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t<th >CODIGO</th>\r\n");
      out.write("\t\t\t\t\t<th >NOMBRE</th>\r\n");
      out.write("\t\t\t\t\t<th >DESCRPCION</th>\r\n");
      out.write("\t\t\t\t\t<th >PRECIO</th>\r\n");
      out.write("\t\t\t\t\t<th ></th>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"col-lg-6 col-sm-12 mt-4 table-responsive\">\r\n");
      out.write("\t\t\t<table id=\"tableDetalle\" class=\"table table-striped table-sm\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t<tr class=\"table-success\">\r\n");
      out.write("\t\t\t\t\t<th >CODIGO</th>\r\n");
      out.write("\t\t\t\t\t<th >NOMBRE</th>\r\n");
      out.write("\t\t\t\t\t<th >DESCRPCION</th>\r\n");
      out.write("\t\t\t\t\t<th >Remitente</th>\r\n");
      out.write("\t\t\t\t\t<th>Total</th>\r\n");
      out.write("\t\t\t\t\t<th ></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("     </div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 text-center mt-4 mb-5\"> \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" id=\"Guardar\" class=\"btn btn-primary me-2\"><i class=\"fas fa-save\"></i> Registrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" id=\"Cancelar\" class=\"btn btn-danger ms-2\" data-dismiss=\"modal\"><i class=\"fas fa-undo-alt\"></i> Cancelar</button>\r\n");
=======
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"row p-3  mb-3\">\r\n");
      out.write("\t<div class=\"col-lg-6 col-ms-12 p-3  mb-3 border cambiarTamano\">\r\n");
      out.write("\t\t<h5 class=\"text-success\">Datos del Detalle</h5>\r\n");
      out.write("\t   <div class=\"col-md-12\">\r\n");
      out.write("\t    <label for=\"validationDefault02\" class=\"form-label\">Cantidad</label>\r\n");
      out.write("\t    <input type=\"text\" class=\"form-control cal-creditoAdeudado\" id=\"idcantidad\" name=\"cantidad\" value=\"\">\r\n");
      out.write("\t  </div>\r\n");
      out.write("\t    <div class=\"col-md-12\">\r\n");
      out.write("\t    <label for=\"validationDefaultUsername\" class=\"form-label\">Descrpción del Daño</label>\r\n");
      out.write("\t\t    <div class=\"form-floating\">\r\n");
      out.write("\t\t\t  <textarea class=\"form-control\" placeholder=\"\" id=\"idDescripDano\" name=\"descripcionDano\" style=\"height: 100px\"></textarea>\r\n");
      out.write("\t\t\t  <label for=\"floatingTextarea2\">Descrpción del Daño</label>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t  </div>\r\n");
      out.write("  \r\n");
      out.write("\t  \t<div class=\"row mt-1\">\t\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-12 col-sm-12 mt-4 table-responsive modificarTamanoTabla\">\r\n");
      out.write("\t\t\t\t<table id=\"tableDetalle\" class=\"table table-striped table-sm\" style=\"width: 100%; font-size: 12px\">\r\n");
      out.write("\t\t\t\t\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t\t<tr class=\"table-success\">\r\n");
      out.write("\t\t\t\t\t    <th >NRO_OC</th>\r\n");
      out.write("\t\t\t\t\t\t<th >CODIGO</th>\r\n");
      out.write("\t\t\t\t\t\t<th >DES-BIEN</th>\r\n");
      out.write("\t\t\t\t\t\t<th >CANT</th>\r\n");
      out.write("\t\t\t\t\t\t<th >PRECIO</th>\r\n");
      out.write("\t\t\t\t\t\t<th >CREDITO</th>\r\n");
      out.write("\t\t\t\t\t\t<th >DES-DAÑO</th>\r\n");
      out.write("\t\t\t\t\t\t<th ></th>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t     </div>\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"col-lg-6 col-sm-12 p-3  mb-3 tablaBiensOcultar\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-12 col-sm-12 mt-4 table-responsive\">\r\n");
      out.write("\t\t\t<table id=\"tableBienes\" class=\"table table-striped table-sm\" style=\"width: 100%; font-size: 12px\">\r\n");
      out.write("\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t<tr >\r\n");
      out.write("\t\t\t\t\t<th >NRO_OC</th>\r\n");
      out.write("\t\t\t\t\t<th >PROVEE</th>\r\n");
      out.write("\t\t\t\t\t<th >CODIGO</th>\r\n");
      out.write("\t\t\t\t\t<th >DESCRPCION</th>\r\n");
      out.write("\t\t\t\t\t<th >CANT-COMP</th>\r\n");
      out.write("\t\t\t\t\t<th >PRE-COMP</th>\r\n");
      out.write("\t\t\t\t\t<th ></th>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-12 text-center mt-4 mb-5\"> \t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" id=\"Guardar\" class=\"btn btn-primary me-2 btn-registrar\"><i class=\"fas fa-save\"></i> Registrar</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"reset\" id=\"Cancelar\" class=\"btn btn-danger ms-2\" data-dismiss=\"modal\"><i class=\"fas fa-undo-alt\"></i> Cancelar</button>\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\t\t</div> \r\n");
      out.write("\r\n");
      out.write("\t\t</form>\r\n");
      out.write("      </div>\r\n");
      out.write("      \t\t\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
<<<<<<< HEAD
      out.write("\t<div class=\"col mt-4\">\r\n");
      out.write("\t\t\t<table id=\"tbexample\" class=\"table table-striped\" style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t<tr class=\"table-success\">\r\n");
      out.write("\t\t\t\t\t<th >Num. de Devolución</th>\r\n");
      out.write("\t\t\t\t\t<th >Fecha de Devolución</th>\r\n");
      out.write("\t\t\t\t\t<th >Proveedor</th>\r\n");
      out.write("\t\t\t\t\t<th >Remitente</th>\r\n");
      out.write("\t\t\t\t\t<th>Total de Devolución</th>\r\n");
      out.write("\t\t\t\t\t<th ></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td><i class=\"bi bi-trash-fill\" style=\"font-size: 1.2rem;\"></i>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary float-end mx-1\">Eliminar</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary float-end mx-1\">Actualizar</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary float-end mx-1\">Generar detalle</button></td>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\t\r\n");
=======
      out.write("\t\r\n");
      out.write("\t<div class=\"col col-sm-12 mt-4 table-responsive\">\r\n");
      out.write("\t\t\t<table id=\"tbexample\" class=\"table table-striped\" style=\"width: 100%; font-size: 12px\">\r\n");
      out.write("\t\t\t\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t<tr class=\"table-success\">\r\n");
      out.write("\t\t\t\t   <th>CODIGO</th>\r\n");
      out.write("\t\t\t\t\t<th>NRO FICHA</th>\r\n");
      out.write("\t\t\t\t\t<th>FECHA</th>\r\n");
      out.write("\t\t\t\t\t<th>PROVEEDOR</th>\r\n");
      out.write("\t\t\t\t\t<th>TOTAL</th>\r\n");
      out.write("\t\t\t\t\t<th>REMITENTE</th>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t<!-- Modal  para ver detalle de devolución-->\r\n");
      out.write("\t\t\r\n");
      out.write("<div class=\"modal fade\" id=\"modalVerDetalleDevolucion\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("  <div class=\"modal-dialog modal-xl\">\r\n");
      out.write("    <div class=\"modal-content\">\r\n");
      out.write("      <div class=\"modal-header\">\r\n");
      out.write("        <h5 class=\"modal-title\" id=\"exampleModalLabel\">Detalle  de Devolución</h5>\r\n");
      out.write("        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"modal-body\">\r\n");
      out.write("      \t\r\n");
      out.write("      \t<div class=\"row mx-3 my-1\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"row mx-3 my-3\">\r\n");
      out.write("\t\t\t\t<div class=\"col-md-6 text-center p-2 lh-sm\">\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t<h7 class=\"fw-bolder\">RUC:20401381291</h7><br>\r\n");
      out.write("\t\t\t\t\t<p>Av Abancay cuadra. 5 S/N, Lima,Perú</p>\r\n");
      out.write("\t\t\t\t\t<p>Telf: 990990215 - 989435229</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-md-3 text-center p-2 lh-sm border\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<h6>Ficha de Devolución</h6>\r\n");
      out.write("\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"mb-2 row g-2 d-flex justify-content-center mr-3\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"inputPassword6\" class=\"col-form-label fw-bolder\">NRO:</label>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" id=\"idnumeroFichadevol\" name=\"numerodevol\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tclass=\"form-control text-primary fw-bold text-center\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-describedby=\"passwordHelpInline\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"col-md-2\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("      \r\n");
      out.write("   \t\t<div class=\"row mt-1\">\t\r\n");
      out.write("\t   \t\t<h5 class=\"text-success\">Datos del Detalle</h5>\r\n");
      out.write("\t   \t\t\t\t<div class=\"col-md-6 col-12\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"mpDepartamento\" class=\"col-6 col-form-label\">Total\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcrédito adeudado</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"idtotalCreditoAdeudonuevo\" name=\"totalCreditoAdeudonuevo\" class=\"form-control text-danger fw-bold\" value=\"0\" readonly=\"readonly\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-12 col-sm-12 mt-4 table-responsive\">\r\n");
      out.write("\t\t\t\t\t<table id=\"tableDetalleDevolucion\" class=\"table table-striped table-sm\" style=\"width: 100%; font-size: 12px\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<thead class=\"table-dark\">\r\n");
      out.write("\t\t\t\t\t\t<tr class=\"table-success\">\r\n");
      out.write("\t\t\t\t\t\t    \r\n");
      out.write("\t\t\t\t\t\t\t<th >CODIGO_DET</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >CODIGO_DEV</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >NRO_DEV</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >NRO_OC</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >TIPO_BIEN</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >COD_BIEN</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >DES_BIEN</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >DES_DAÑO</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >PRECIO</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >CANT</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th >CREDITO</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th ></th>\r\n");
      out.write("\t\t\t\t\t\t\t<th ></th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t     </div>\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("      \t\t\r\n");
      out.write("      <div class=\"modal-footer\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t  \t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Modal para Eliminar Devolucion-->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"modalElimimar\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t        <h7 class=\"modal-title\" id=\"exampleModalLabel\">Sistema</h7>\r\n");
      out.write("\t\t\t\t\t        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t        \t<form id=\"idEliminar\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\t\taction=\"ServletDevolucionBien?tipo=ELIMINARDEVOLUCION\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" name=\"codigoEliminar\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"codigoEliminar\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>¿Seguro de eliminar?</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">SI</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">NO</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t<!-- Modal para Eliminar Detalle de Devolucion-->\r\n");
      out.write("\t\t\t\t\t<div class=\"modal fade\" id=\"modalElimimarDetalleDevol\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t  <div class=\"modal-dialog\">\r\n");
      out.write("\t\t\t\t\t    <div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t      <div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t        <h7 class=\"modal-title\" id=\"exampleModalLabel\">Sistema</h7>\r\n");
      out.write("\t\t\t\t\t        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t      <div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t        \t<form id=\"idEliminarDetalleDevol\" method=\"post\"\r\n");
      out.write("\t\t\t\t\t\t\taction=\"ServletDevolucionBien?tipo=ELIMINARDETALLEDEVOL\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" name=\"codDetalleDevol\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"codDetalleDevol\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" name=\"numeroFichaDevol\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"numeroFichaDevol\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"hidden\" class=\"form-control\" name=\"nuevoTotalCreditoAdeudo\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"nuevoTotalCreditoAdeudo\">\r\n");
      out.write("\t\t\t\t\t\t\t<h6>¿Seguro de eliminar?</h6>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-primary\">SI</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-bs-dismiss=\"modal\">NO</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t      </div>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("</div>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
<<<<<<< HEAD
=======
      out.write("<script src=\"//code.jquery.com/jquery-3.2.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"jquery.dynamicTable.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
>>>>>>> NelsonCriollo
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
<<<<<<< HEAD
      out.write("\t\t\t<script\r\n");
=======
      out.write("\t\t<script\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.datatables.net/1.11.5/js/dataTables.bootstrap5.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- JS para validación-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.bootcdn.net/ajax/libs/bootstrap-validator/0.4.0/js/bootstrapValidator.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js\"></script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcargarBines();\r\n");
<<<<<<< HEAD
=======
      out.write("\t\tllenarcboProveedor();\r\n");
      out.write("\t\t//cargarNumeroFichaDevol();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t //fuciones para obtener el núemro de ficha de devolución\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-generaFichaDevol\",function(){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.get(\"ServletDevolucionBien?tipo=GENERARNUM\",function(response){\r\n");
      out.write("\t\t\t\t\t$(\"#idnumerodevol\").val(response);\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#idIdentificador\").val(0); //pasamos el valor de uno como indicadorpara actualizar\r\n");
      out.write("\t\t\t\t\t $('.tablaBiensOcultar').show(); //mostrar\r\n");
      out.write("\t\t\t\t\t$('.modificarTamano'). removeClass('modal-xl');\r\n");
      out.write("\t\t\t\t\t $('.modificarTamano').addClass('modal-fullscreen');\r\n");
      out.write("\t\t\t\t\t $('.cambiarTamano').removeClass('col-lg-12 m-auto');\r\n");
      out.write("\t\t\t\t\t $('.cambiarTamano').addClass('col-lg-6 col-ms-12 p-3  mb-3');\r\n");
      out.write("\t\t\t\t\t $('.cambiarTamano').show();  \r\n");
      out.write("\t\t\t\t\t $('.divCodigoDevolOculto').hide(); //ocultar\r\n");
      out.write("\t\t\t\t\t \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t $('.btn-registrar').text(\"Registrar\"); // para cambiar el texto del boton registrar\r\n");
      out.write("\t\t\t\t\t $('.btn-registrar').prop('disabled', false);// para habilitar el  boton registrar\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
>>>>>>> NelsonCriollo
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction cargarBines(){\r\n");
      out.write("\t\t\r\n");
<<<<<<< HEAD
      out.write("\t\t\t$.get(\"ServletBienesJSON\",function(response){\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableBienes\").append(\"<tr><td>\"+item.cod_bien+\"</td><td>\"+item.nombre+\"</td><td>\"+item.descripcion+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<button type='button' class='btn btn-outline-success btn-adicionar'><i class=' text-write fas fa-plus-circle'></i></button></td></tr>\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$('#tableBienes').DataTable();\r\n");
=======
      out.write("\t\t\t$.get(\"Servlet_OC_DetalleOC_JSON\",function(response){\r\n");
      out.write("\t\t\t\t$(\"#tableBienes tbody\").empty();\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableBienes\").append(\"<tr><td>\"+item.ordenCompra.nroOrdencompra+\"</td><td>\"+item.ordenCompra.nomProveedor+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.bien.cod_bien+\"</td><td>\"+item.bien.descripcion+\"</td><td>\"+item.cantidad+\"</td><td>\"+item.precioUnitario+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<button type='button' class='btn btn-outline-success btn-adicionar me-1  p-1 text-center'><i class=' text-write fas fa-plus-circle'></i></button></td></tr>\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$('#tableBienes').DataTable();\r\n");
      out.write("\t\t\t\t\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
<<<<<<< HEAD
      out.write("\t\t//asignar evento click a todos los botones con clase \"btn-adicionar\"\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-adicionar\",function(){\r\n");
      out.write("\t\t\tlet cod,des,cant,prec,creditoAdeu;\r\n");
      out.write("\t\t\tcod=$(\"#idBien\").val();\r\n");
      out.write("\t\t\tdes=$(\"#idDescrip\").val();\r\n");
      out.write("\t\t\tcant=$(\"#idcantidad\").val();\r\n");
      out.write("\t\t\tprec=$(\"#idprecio\").val();\r\n");
      out.write("\t\t\tcreditoAdeu=$(\"#idcreditoAdeudado\").val();\r\n");
      out.write("\t\t\t$.get(\"ServletDevolucionBien?tipo=ADICIONAR\",{\"codigo\":cod,\"descripcionDano\":des,\"cantidad\":cant,\"precio\":prec,\"creditoAdeudado\":creditoAdeu},function(response){\r\n");
      out.write("\t\t\t\tconsole.log(response);\r\n");
      out.write("\t\t\t\t$(\"#tableDetalle tbody\").empty();\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableDetalle\").append(\"<tr><td>\"+item.id_Bien+\"</td><td>\"+item.descripcion_del_dano+\"</td><td>\"+item.precioCompra+\"</td><td>\"+item.cantidad+\"</td><td>\"+item.credito_adeudado+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<button type='button' class='btn btn-outline-danger btn-eliminar'><i class='fas fa-backspace'></i></button></td></tr>\");\r\n");
      out.write("\t\t\t\t})\r\n");
=======
      out.write("\t\t //fuciones para llenar los select\r\n");
      out.write("\t\t function llenarcboProveedor(){\r\n");
      out.write("\t\t\t$.get(\"ServletProveedorJSON\",function(response){\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#idProveedor\").append(\"<option value='\"+item.id_proveedor+\"'>\"+item.razon_social+\"</option>\");\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t \r\n");
      out.write("\r\n");
      out.write("\t\t//asignar evento click a todos los botones con clase \"btn-adicionar\"\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-adicionar\",function(){\r\n");
      out.write("\t\t\tlet nroOC,cod,desBien,cant,prec,creditoAdeu,suma=0;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tnroOC=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\tcod=$(this).parents(\"tr\").find(\"td\")[2].innerHTML;\r\n");
      out.write("\t\t\tdesBien=$(this).parents(\"tr\").find(\"td\")[3].innerHTML;\r\n");
      out.write("\t\t\tprec=$(this).parents(\"tr\").find(\"td\")[5].innerHTML;\r\n");
      out.write("\t\t\tdesDano=$(\"#idDescripDano\").val();\r\n");
      out.write("\t\t\tcant=$(\"#idcantidad\").val();\r\n");
      out.write("\t\t\tcreditoAdeu=(prec*cant);\r\n");
      out.write("\t\t\t$.get(\"ServletDevolucionBien?tipo=ADICIONAR\",{\"nroOC\":nroOC,\"codigoBien\":cod,\"desBien\":desBien,\"descripcionDano\":desDano,\"precio\":prec,\"cantidad\":cant,\"creditoAdeudado\":creditoAdeu},function(response){\r\n");
      out.write("\t\t\t\t$(\"#tableDetalle tbody\").empty();\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableDetalle\").append(\"<tr><td>\"+item.nro_orden_compra+\"</td><td>\"+item.id_Bien+\"</td><td>\"+item.desBien+\"</td><td>\"+item.precioCompra+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.cantidad+\"</td><td>\"+item.credito_adeudado+\"</td><td>\"+item.descripcion_del_dano+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<button type='button' class='btn btn-outline-danger btn-eliminar p-1 text-center'><i class='fas fa-backspace'></i></button></td></tr>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsuma += parseFloat(item.credito_adeudado);\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\tconsole.log(suma);\r\n");
      out.write("\t\t\t\t$(\"#idtotalCreditoAdeudo\").val(suma);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//asignar evento click a todos los botones con clase \"btn-eliminar\"\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-eliminar\",function(){\r\n");
      out.write("\t\t\tlet cod,suma=0;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcod=$(this).parents(\"tr\").find(\"td\")[1].innerHTML;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.get(\"ServletDevolucionBien?tipo=ELIMINAR\",{\"codigoBien\":cod},function(response){\r\n");
      out.write("\t\t\t\t$(\"#tableDetalle tbody\").empty();\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableDetalle\").append(\"<tr><td>\"+item.nro_orden_compra+\"</td><td>\"+item.id_Bien+\"</td><td>\"+item.desBien+\"</td><td>\"+item.precioCompra+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.cantidad+\"</td><td>\"+item.credito_adeudado+\"</td><td>\"+item.descripcion_del_dano+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<button type='button' class='btn btn-outline-danger btn-eliminar p-1 text-center'><i class='fas fa-backspace'></i></button></td></tr>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsuma += parseFloat(item.credito_adeudado);\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$(\"#idtotalCreditoAdeudo\").val(suma);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//asignamos evento a todos los botones(\"editar\") con nombre de clase \"btn-editar\"\r\n");
      out.write("\t\t$(document).on(\"click\", \".btn-editar\", function() {\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t $(\"#idIdentificador\").val(1); //pasamos el valor de uno como indicadorpara actualizar\r\n");
      out.write("\t\t\t $('.tablaBiensOcultar').hide(); //ocultar\r\n");
      out.write("\t\t\t $('.cambiarTamano').hide(); \r\n");
      out.write("\t\t\t $('.divCodigoDevolOculto').show(); //mostrar\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t $('.modificarTamano').removeClass('modal-fullscreen');\r\n");
      out.write("\t\t\t $('.modificarTamano').addClass('modal-xl');\r\n");
      out.write("\t\t\t $('.cambiarTamano').addClass('col-lg-12 m-auto');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t $('.btn-registrar').text(\"Actualizar\"); // para cambiar el texto del boton registrar\r\n");
      out.write("\t\t\t //$('.btn-registrar').prop('disabled', false);// para habilitar el  boton registrar\r\n");
      out.write("\t\t     $(\"#idDescripDano\").val(\"\");\r\n");
      out.write("\t\t     $(\"#codigodevol\").val(\"\");\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\tlet codigo;\r\n");
      out.write("\t\t\t //obtenemos el valor de la columna(0), para paserle como parametro al ServletAccesoJSON\r\n");
      out.write("\t\t\tcodigo = $(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.get(\"ServletDevolucionBienJSON\",{\"codigo\":codigo},function(response){\r\n");
      out.write("\t\t\t\tconsole.log(response);\r\n");
      out.write("\t\t\t\t//$(\"#idBien\").val(response.cod_bien);\r\n");
      out.write("\t\t\t\t$(\"#idcodigodevol\").val(response.id_Devolucion);\r\n");
      out.write("\t\t\t\t$(\"#idnumerodevol\").val(response.nro_ficha);\r\n");
      out.write("\t\t\t\t$('#idFechaDevolucion').val(formatearFechaYMD(response.fecha));\r\n");
      out.write("\t\t\t\t$(\"#idRemitente\").val(response.nomRemitente);\r\n");
      out.write("\t\t\t\t$(\"#idProveedor\").val(response.proveedor.id_proveedor);\r\n");
      out.write("\t\t\t\t$(\"#idtotalCreditoAdeudo\").val(response.total_credito_adeudado);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//cargar el detalle de la devolucion editada\r\n");
      out.write("\t\t\t$.get(\"ServletDeatalleDevolucionJSON\",{\"codDevol\":codigo},function(response){\r\n");
      out.write("\t\t\t\t console.log(response);\r\n");
      out.write("\t\t\t\t$(\"#tableDetalle tbody\").empty();\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableDetalle\").append(\"<tr><td name='tdNumOc'>\"+item.ordenCompra.nroOrdencompra+\"</td><td name='tdCodBien'>\"+item.bien.cod_bien+\"</td><td name='tdDesBien'>\"+item.bien.descripcion+\"</td><td name='tdPrecCompra'>\"+item.precioCompra+\r\n");
      out.write("\t\t\t\t\t\t\t\"</td><td name='tdCantidad'>\"+item.cantidad+\"</td><td name='tdCredito'>\"+item.credito_adeudado+\"</td><td name='tdDesDano'>\"+item.descripcion_del_dano+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<button type='button' class='btn btn-outline-danger btn-eliminar p-1 text-center'><i class='fas fa-backspace'></i></button></td></tr>\");\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t//asignar evento click a todos los botones con clase \"btn-verDetalle\"\r\n");
      out.write("\t\t$(document).on(\"click\",\".btn-verDetalle\",function(){\r\n");
      out.write("\t\t\tlet codigo,numficha,suma=0;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tcodigo=$(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\tnumficha=$(this).parents(\"tr\").find(\"td\")[1].innerHTML;\r\n");
      out.write("\t\t\t$(\"#idnumeroFichadevol\").val(numficha);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.get(\"ServletDeatalleDevolucionJSON\",{\"codDevol\":codigo},function(response){\r\n");
      out.write("\t\t\t\t console.log(response);\r\n");
      out.write("\t\t\t\t$(\"#tableDetalleDevolucion tbody\").empty();\r\n");
      out.write("\t\t\t\t$.each(response,function(index,item){\r\n");
      out.write("\t\t\t\t\t$(\"#tableDetalleDevolucion\").append(\"<tr><td>\"+item.id_DetalleDevolucion+\"</td><td>\"+item.devolucion.id_Devolucion+\"</td><td>\"+item.devolucion.nro_ficha+\"</td><td>\"+item.ordenCompra.nroOrdencompra+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\titem.bien.nombreTipo+\"</td><td>\"+item.bien.cod_bien+\"</td><td>\"+item.bien.descripcion+\"</td><td>\"+item.descripcion_del_dano+\"</td><td>\"+item.precioCompra+\"</td><td>\"+item.cantidad+\"</td><td>\"+item.credito_adeudado+\"</td><td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<button type='button' class='btn btn-outline-danger btn-eliminarDetalle p-1 text-center' data-bs-toggle='modal' data-bs-target='#modalElimimarDetalleDevol'><i class='fas fa-backspace'></i></button></td></tr>\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tsuma += parseFloat(item.credito_adeudado);\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t$(\"#idtotalCreditoAdeudonuevo\").val(suma);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
>>>>>>> NelsonCriollo
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
<<<<<<< HEAD
      out.write("\t\t\r\n");
      out.write("\t\t</script>\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar popoverTriggerList = [].slice.call(document\r\n");
      out.write("\t\t\t\t.querySelectorAll('[data-bs-toggle=\"popover\"]'))\r\n");
      out.write("\t\tvar popoverList = popoverTriggerList.map(function(popoverTriggerEl) {\r\n");
      out.write("\t\t\treturn new bootstrap.Popover(popoverTriggerEl)\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("    $('#tbexample').DataTable();\r\n");
      out.write("    $('#tableDetalle').DataTable();\r\n");
      out.write("    $('#tableBienes').DataTable();\r\n");
      out.write("   \r\n");
      out.write("} );\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
=======
      out.write("\t\t//funcion para eliminar por código\r\n");
      out.write("\t\t$(document).on(\"click\", \".btn-outline-danger\", function() {\r\n");
      out.write("\t\t\t//variable\r\n");
      out.write("\t\t\tlet codigo;\r\n");
      out.write("\t\t\t//obtener el código del Acceso según el botón eliminar que se a pulsado\r\n");
      out.write("\t\t\tcodigo = $(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\t//asignar a la caja con id \"codigoEliminar\" el valor de la variable \"codigo\"\r\n");
      out.write("\t\t\t$(\"#codigoEliminar\").val(codigo);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//$.get(\"ServletDevolucionBien?tipo=LISTAR\",function(response){\r\n");
      out.write("\t\t\t\t//$(\"#idnumerodevol\").val(response);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t//})\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t//funcion para eliminar Detalle de devolución por código\r\n");
      out.write("\t\t$(document).on(\"click\", \".btn-eliminarDetalle\", function() {\r\n");
      out.write("\t\t\t//variable\r\n");
      out.write("\t\t\tlet codigoDetalle,nroFichaDevol,nuevoTotalCredito;\r\n");
      out.write("\t\t\t//obtener el código del Acceso según el botón eliminar que se a pulsado\r\n");
      out.write("\t\t\tcodigo = $(this).parents(\"tr\").find(\"td\")[0].innerHTML;\r\n");
      out.write("\t\t\tnroFichaDevol=$('#idnumeroFichadevol').val();\r\n");
      out.write("\t\t\tnuevoTotalCredito=$('#idtotalCreditoAdeudonuevo').val();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//asignar a la caja con id \"codigoEliminar\" el valor de la variable \"codigo\"\r\n");
      out.write("\t\t\t$(\"#codDetalleDevol\").val(codigo);\r\n");
      out.write("\t\t\t$(\"#numeroFichaDevol\").val(nroFichaDevol);\r\n");
      out.write("\t\t\t$(\"#nuevoTotalCreditoAdeudo\").val(nuevoTotalCredito);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//$.get(\"ServletDevolucionBien?tipo=LISTAR\",function(response){\r\n");
      out.write("\t\t\t\t//$(\"#idnumerodevol\").val(response);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t//})\r\n");
      out.write("\r\n");
      out.write("\t\t})\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\tfunction formatearFechaYMD(fech){\r\n");
      out.write("\t\t\tvar Vfecha = new Date(fech);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar VDia=Vfecha.getDate();\r\n");
      out.write("\t\t\tvar VMes=Vfecha.getMonth()+1;\r\n");
      out.write("\t\t\tvar VYear=Vfecha.getFullYear();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tVDia=VDia<10? \"0\"+VDia: VDia;\r\n");
      out.write("\t\t\tVMes=VMes<10? \"0\"+VMes: VMes;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn  VYear+\"-\"+VMes+\"-\"+VDia;\r\n");
      out.write("\t\t\tconsole.log(VYear+\"-\"+VMes+\"-\"+VDia);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\tvar popoverTriggerList = [].slice.call(document\r\n");
      out.write("\t\t\t\t\t.querySelectorAll('[data-bs-toggle=\"popover\"]'))\r\n");
      out.write("\t\t\tvar popoverList = popoverTriggerList.map(function(popoverTriggerEl) {\r\n");
      out.write("\t\t\t\treturn new bootstrap.Popover(popoverTriggerEl)\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t\t$(document).ready(function() {\r\n");
      out.write("\t\t    \t$('#tbexample').DataTable();\r\n");
      out.write("\t\t\t} );\r\n");
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
>>>>>>> NelsonCriollo
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t$('.toast').toast('show');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /Mantenimiento_Devolucion_de_Bienes.jsp(49,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MENSAJE!=null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t<div class=\"toast bg-black mx-auto mt-2\" role=\"alert\"\r\n");
          out.write("\t\t\taria-live=\"assertive\" aria-atomic=\"true\" data-bs-delay=\"3000\">\r\n");
          out.write("\t\t\t<div class=\"toast-header\">\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t<button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"toast\"\r\n");
          out.write("\t\t\t\t\taria-label=\"Close\"></button>\r\n");
          out.write("\t\t\t</div>\r\n");
          out.write("\t\t\t<div class=\"toast-body text-light\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.MENSAJE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("\t\t</div>\r\n");
          out.write("\r\n");
          out.write("\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
<<<<<<< HEAD
=======

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /Mantenimiento_Devolucion_de_Bienes.jsp(282,5) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.listaDevoluciones}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /Mantenimiento_Devolucion_de_Bienes.jsp(282,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("row");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\t\t\t\t\t\t\t\t<tr>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.id_Devolucion}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-primary\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.nro_ficha}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-info\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.fecha}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.proveedor.razon_social}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td class=\"text-danger\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.total_credito_adeudado}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t<td>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${row.nomRemitente}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</td>\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t<td><button type=\"button\" class=\"btn btn-outline-dark btn-editar p-1 text-center\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">\r\n");
            out.write("\t\t\t\t\t<i class=\"fas fa-edit\"></i></button></td>\r\n");
            out.write("\t\t\t\t\t<td><button type=\"button\" class=\"btn btn-outline-success btn-verDetalle p-1 text-center\" data-bs-toggle=\"modal\" data-bs-target=\"#modalVerDetalleDevolucion\" >\r\n");
            out.write("\t\t\t\t\t<i class=\"fas fa-binoculars\"></i></button></td>\r\n");
            out.write("\t\t\t\t\t<td><button type=\"button\" class=\"btn btn-outline-danger btn-eliminar-Devolucion p-1 text-center\" data-bs-toggle=\"modal\" data-bs-target=\"#modalElimimar\">\r\n");
            out.write("\t\t\t\t\t<i class=\"fas fa-backspace\"></i></button></td>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t\t</tr>\r\n");
            out.write("\t\t\t\t\t");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }
>>>>>>> NelsonCriollo
}
