/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2022-06-12 23:45:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Mantenimiento_005fDevolucion_005fde_005fBienes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\n");
      out.write("<div id=\"principal\" class=\"container\">\n");
      out.write("\t<div class=\"row mx-5 my-4\">\n");
      out.write("\t\t<div class=\"col-md-6 text-center p-5 lh-sm\">\n");
      out.write("\n");
      out.write("\t\t\t<h5 class=\"fw-bold\">Registro de Devolución de Bienes</h5>\n");
      out.write("\t\t\t<p>Av Abancay cuadra. 5 S/N, Lima,Perú</p>\n");
      out.write("\t\t\t<p>Telf: 990990215 - 989435229</p>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"col-md-4 text-center p-3 lh-sm border border-secondary\">\n");
      out.write("\t\t\t<h3>RUC:20401381291</h3>\n");
      out.write("\t\t\t<h3>FICHA DE DEVOLUCIÓN</h3>\n");
      out.write("\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t<div class=\" mb-2 row g-3 d-flex justify-content-center mr-3\">\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<label for=\"inputPassword6\" class=\"col-form-label\">NRO:</label>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"inputPassword6\" class=\"form-control\"\n");
      out.write("\t\t\t\t\t\t\taria-describedby=\"passwordHelpInline\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"col-md-2\"></div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<div class=\"row\">\n");
      out.write("\t\t<h3>Datos de Registro de Devoluciones</h3>\n");
      out.write("\t\t<form class=\"form-horizontal border border-secondary\">\n");
      out.write("\t\t\t<div class=\"row p-3\">\n");
      out.write("\t\t\t\t<div class=\"col-md-10 col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"txtFechaDevolucion\" class=\" col-6 col-form-label\">Fecha\n");
      out.write("\t\t\t\t\t\t\t\t\tde Devolución</label>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"date\" id=\"txtFechaDevolucion\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"mpDepartamento\" class=\"col-6 col-form-label\">Remitente</label>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"mpDepartamento\" class=\"form-select\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option selected>Seleccionar</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"txtProveedor\" class=\" col-6 col-form-label\">Proveedor</label>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<select id=\"txtProveedor\" class=\"form-select\">\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option selected>Seleccionar</option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<option></option>\n");
      out.write("\t\t\t\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t<div class=\"col-md-6 col-12\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"row my-1\">\n");
      out.write("\t\t\t\t\t\t\t\t<label for=\"mpDepartamento\" class=\"col-6 col-form-label\">Total\n");
      out.write("\t\t\t\t\t\t\t\t\tcrédito adeudado</label>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"col-6\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" id=\"mpDepartamento\" class=\"form-control\">\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"col-md-2 col-12\">\n");
      out.write("\t\t\t\t\t<div class=\"row my-1\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12 d-grid\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-dark\" type=\"submit\">Nuevo</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"row my-1\">\n");
      out.write("\t\t\t\t\t\t<div class=\"col-lg-12 d-grid\">\n");
      out.write("\t\t\t\t\t\t\t<button class=\"btn btn-dark\" type=\"submit\">Grabar</button>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t</form>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"row mt-3\">\n");
      out.write("\t\t<table id=\"TablaDevolucionBienes\" class=\"table table-striped\">\n");
      out.write("\t\t\t<thead>\n");
      out.write("\t\t\t\t<tr class=\"table-success\">\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Num. de Devolución</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Fecha de Devolución</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Proveedor</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Remitente</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\">Total de Devolución</th>\n");
      out.write("\t\t\t\t\t<th scope=\"col\"></th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</thead>\n");
      out.write("\t\t\t<tbody>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td></td>\n");
      out.write("\t\t\t\t\t<td><i class=\"bi bi-trash-fill\" style=\"font-size: 1.2rem;\"></i>\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary float-end mx-1\">Eliminar</button>\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary float-end mx-1\">Actualizar</button>\n");
      out.write("\t\t\t\t\t\t<button class=\"btn btn-secondary float-end mx-1\">Generar detalle</button></td>\n");
      out.write("\t\t\t</tbody>\n");
      out.write("\t\t</table>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- INICIO - Modal EDITAR-->\n");
      out.write("\t\t\t\t<div class=\"modal fade\" id=\"modalMantenimientoDevolucionBienes\" data-backdrop=\"static\" data-keyboard=\"false\" tabindex=\"-1\" aria-labelledby=\"staticBackdropLabel\" aria-hidden=\"true\">\n");
      out.write("\t\t\t\t  <div class=\"modal-dialog modal-dialog-centered\">\n");
      out.write("\t\t\t\t    <div class=\"modal-content\">\n");
      out.write("\t\t\t\t      <div class=\"modal-header\">\n");
      out.write("\t\t\t\t        <h5 class=\"modal-title\" id=\"staticBackdropLabel\">SUPERVISOR</h5>\n");
      out.write("\t\t\t\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t\t\t\t          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t\t\t        </button>\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t      <div class=\"modal-body\">\n");
      out.write("\t\t\t\t        <form id=\"formDocente\" method=\"post\" action=\"ServletSupervisor\">\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputEmail1\">Num. de Devolución</label>\n");
      out.write("\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"cod_supervisor\" name=\"codigo\" readonly>\n");
      out.write("\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t    <label for=\"idDescripcion\">Fecha de Devolución\t</label>\n");
      out.write("\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"nom_supervisor\" readonly>\n");
      out.write("\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputPassword1\">Proveedor</label>\n");
      out.write("\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"ape_supervisor\" readonly>\n");
      out.write("\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputPassword1\">Remitente</label>\n");
      out.write("\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"dni_supervisor\" readonly>\n");
      out.write("\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputPassword1\">Total de Devolución\t</label>\n");
      out.write("\t\t\t\t\t\t    <input type=\"text\" class=\"form-control\" id=\"num_hijos\" readonly>\n");
      out.write("\t\t\t\t\t\t  </div>\n");
      out.write("\t\t\t\t\t\t  <div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t    <label for=\"exampleInputPassword1\">Sucursal</label>\n");
      out.write("\t\t\t\t\t\t    <select class=\"form-control\" name=\"condicion\" id=\"idEditarSucursal\">\n");
      out.write("\t\t\t\t\t\t      <option value=\" \">[Seleccione Sucursal]</option>\n");
      out.write("\t\t\t\t\t\t    </select>\n");
      out.write("\t\t\t\t\t\t  </div>\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t  \n");
      out.write("\t\t\t\t\t\t  <div class=\"modal-footer\">\n");
      out.write("\t\t\t\t\t      \t<button type=\"submit\" class=\"btn btn-primary\">Eliminar</button>\n");
      out.write("\t\t\t\t\t        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Cerrar</button>\n");
      out.write("\t\t\t\t\t      </div>\n");
      out.write("\t\t\t\t\t\t</form>\n");
      out.write("\t\t\t\t      </div>\n");
      out.write("\t\t\t\t    </div>\n");
      out.write("\t\t\t\t  </div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<!-- FIN - Modal PARA EDITAR-->\t\t\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
