/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2022-06-26 05:23:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class MovimientoInventario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1653951253000L));
    _jspx_dependants.put("jar:file:/C:/Users/Nelcriollo/Desktop/ProyectoFinal_LPII/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProyectoFinal_LPII/WEB-INF/lib/standard.jar!/META-INF/c-1_0-rt.tld", Long.valueOf(1098729090000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Movimiento de Inventario de Bienes</title>\r\n");
      out.write("\r\n");
      out.write("<!--  jquery-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\" https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Los iconos tipo Solid de Fontawesome-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.8.1/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\"\r\n");
      out.write("\tintegrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<!-- Los estilos de Bootstrap-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- Los estilos locales de la carpeta css de proyecto-->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<form class=\"row mx-5 my-4\">\r\n");
      out.write("\t\t<div class=\"col-md-6 text-center p-3 lh-sm\">\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<h5>Control de Inventario de Bienes</h5>\r\n");
      out.write("\t\t\t<p>Av Abancay cuadra. 5 S/N, Lima,Perú</p>\r\n");
      out.write("\t\t\t<p>Telf: 990990215 - 989435229</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3 text-center p-3 lh-sm border border-secondary\">\r\n");
      out.write("\t\t\t<h3>RUC:20401381291</h3>\r\n");
      out.write("\t\t\t<h3>Registro de Control de Inventario</h3>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"mb-2 row g-3 d-flex justify-content-center mr-3\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\r\n");
      out.write("\t\t\t\t\t<label for=\"inputPassword6\" class=\"col-form-label\">NRO:</label>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-auto\">\r\n");
      out.write("\t\t\t    \t\t<input type=\"text\" id=\"inputPassword6\" class=\"form-control\" aria-describedby=\"passwordHelpInline\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"row mx-1 my-1 mb-2\">\r\n");
      out.write("\t\t<h1>Datos de los Bienes Ingresados</h1>\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\r\n");
      out.write("\t<form class=\"row mx-5 my-3 p-3 border border-secondary\">\t\r\n");
      out.write("\t\t<!-- Primer nivel -->\r\n");
      out.write("\t\t<div class=\"col-md-3 mb-2\">\r\n");
      out.write("\t\t    <label for=\"inputState\" class=\"form-label\">Tipo de Inventario</label>\r\n");
      out.write("\t\t    <select id=\"saTipoIventario\" class=\"form-select\">\r\n");
      out.write("\t\t      <option selected>Seleccionar</option>\r\n");
      out.write("\t\t      <option>Tipo1</option>\r\n");
      out.write("\t\t      <option>Tipo2</option>\r\n");
      out.write("\t\t      <option>Tipo3</option>\r\n");
      out.write("\t\t    </select>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-1 mb-2\">\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t<div class=\"col-md-5 mb-2\">\r\n");
      out.write("\t\t  \t<label for=\"inputEmail4\" class=\"form-label\">Descripción</label>\r\n");
      out.write("\t\t    <input type=\"email\" class=\"form-control\" id=\"saDescripcion\">\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t<div class=\"col-md-1 mb-2\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-2 mb-2\">\r\n");
      out.write("\t\t  \t<button class=\"btn btn-dark m-1 mt-4 col-md-7 p-1\" type=\"submit\">Nuevo</button>\t\t    \r\n");
      out.write("\t\t</div>\t\r\n");
      out.write("\t\t<!-- Segundo nivel -->\t\t\r\n");
      out.write("\t\t<div class=\"col-md-3 mb-2\">\r\n");
      out.write("\t\t    <label for=\"inputState\" class=\"form-label\">Fecha de Entrega</label>\r\n");
      out.write("\t\t    <input type=\"date\" id=\"saFechaEntrega\" class=\"form-control\" aria-describedby=\"passwordHelpInline\">\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t<div class=\"col-md-1 mb-2\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-2 mb-2\">\r\n");
      out.write("\t\t    <label for=\"inputPassword4\" class=\"form-label\">Cantidad</label>\r\n");
      out.write("\t\t    <input type=\"email\" class=\"form-control\" id=\"saCantidad\">\r\n");
      out.write("\t\t</div>\t\t\r\n");
      out.write("\t\t<div class=\"col-md-4 mb-2\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"col-md-2 mb-2\">\r\n");
      out.write("\t\t  \t<button class=\"btn btn-dark m-1 mt-4 col-md-7 p-1\" type=\"submit\">Grabar</button>\t\t    \r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- Tercer nivel -->\r\n");
      out.write("\t\t<div class=\"col-md-3 mb-2\">\r\n");
      out.write("\t\t  \t<label for=\"inputEmail4\" class=\"form-label\">Código Bienes</label>\r\n");
      out.write("\t\t    <input type=\"email\" class=\"form-control\" id=\"saCodigoBienes\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Section: Tabla -->\r\n");
      out.write("\t<div class=\"row mx-4 my-2 mb-5\">\t\r\n");
      out.write("\t\t<table id=\"example\" class=\"table table-bordered table-hover mx-1 my-2 mb-3\">\r\n");
      out.write("\t\t  \t<thead>\r\n");
      out.write("\t\t    \t<tr class=\"text-center text-white\" style=\"background-image: radial-gradient(circle at 119.64% 37.72%, #18344a 0, #010912 50%, #000000 100%);\">\r\n");
      out.write("\t\t\t      <th scope=\"col\">CÓDIGO</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">TIPO DE MOVIMIENTO</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">TIPO DE BIEN</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">CODIGO BIENES</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">CANTIDAD</th>\r\n");
      out.write("\t\t\t      <th scope=\"col\">DESCRIPCION</th>\r\n");
      out.write("\t\t\t      \t<th scope=\"col\">EDITAR</th>\r\n");
      out.write("\t\t      \t\t<th scope=\"col\">ELIMINAR</th>\r\n");
      out.write("\t\t    \t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t<tbody>\r\n");
      out.write("\t\t\t    <tr>      \r\n");
      out.write("\t\t\t\t    <td>1</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba SAC</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba SAC</td>      \r\n");
      out.write("\t\t\t\t    <td>202020203698521</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba@gmail.com</td>\r\n");
      out.write("\t\t\t\t    <td>Av. Prueba #150</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#modalRegistrar\">Editar</button></td>\r\n");
      out.write("\t\t\t        <td><button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#modalEliminar\">Eliminar</button></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>      \r\n");
      out.write("\t\t\t\t    <td>1</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba SAC</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba SAC</td>      \r\n");
      out.write("\t\t\t\t    <td>202020203698521</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba@gmail.com</td>\r\n");
      out.write("\t\t\t\t    <td>Av. Prueba #150</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#modalRegistrar\">Editar</button></td>\r\n");
      out.write("\t\t\t        <td><button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#modalEliminar\">Eliminar</button></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t    <tr>      \r\n");
      out.write("\t\t\t\t    <td>1</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba SAC</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba SAC</td>      \r\n");
      out.write("\t\t\t\t    <td>202020203698521</td>\r\n");
      out.write("\t\t\t\t    <td>Prueba@gmail.com</td>\r\n");
      out.write("\t\t\t\t    <td>Av. Prueba #150</td>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<td><button type=\"button\" class=\"btn btn-success\" data-bs-toggle=\"modal\" data-bs-target=\"#modalRegistrar\">Editar</button></td>\r\n");
      out.write("\t\t\t        <td><button type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\" data-bs-target=\"#modalEliminar\">Eliminar</button></td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t</tbody>\r\n");
      out.write("\t\t</table>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"\r\n");
      out.write("\t\t\tintegrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\"\r\n");
      out.write("\t\t\tcrossorigin=\"anonymous\">\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\">\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- JS para validación-->\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.bootcdn.net/ajax/libs/bootstrap-validator/0.4.0/js/bootstrapValidator.js\">\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar popoverTriggerList = [].slice.call(document\r\n");
      out.write("\t\t\t\t.querySelectorAll('[data-bs-toggle=\"popover\"]'))\r\n");
      out.write("\t\tvar popoverList = popoverTriggerList.map(function(popoverTriggerEl) {\r\n");
      out.write("\t\t\treturn new bootstrap.Popover(popoverTriggerEl)\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
