/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2022-06-07 22:07:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class quienes_005fsomos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/Nelcriollo/Desktop/ProyectoFinal_LPII/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ProyectoFinal_LPII/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098729090000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1653951253000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

 
if (request.getSession().getAttribute("LISTAMenu") == null)
	response.sendRedirect("login.jsp");

      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\" https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- Los iconos tipo Solid de Fontawesome-->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.8.1/css/all.css\"\r\n");
      out.write("\tintegrity=\"sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css\"\r\n");
      out.write("\tintegrity=\"sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==\"\r\n");
      out.write("\tcrossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("\t\r\n");
      out.write("<!-- Los estilos de Bootstrap-->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\"\r\n");
      out.write("\tintegrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\"\r\n");
      out.write("\tcrossorigin=\"anonymous\">\r\n");
      out.write("\t\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("\t\t\t<section class=\"page-section portfolio\" id=\"portfolio\">\r\n");
      out.write("        \t<div class=\"container\">\r\n");
      out.write("\t\t\t<h1 class=\"text-center mt-5\">¿Quiénes Somos?<img src=\"img/somos.png\" class=\"img-thumbnail\" width=\"100\" height=\"70\"class=\"d-inline-block align-text-top\"></h1>\r\n");
      out.write("\t\t\t<div class=\"divider-custom\">\r\n");
      out.write("               <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                <div class=\"divider-custom-line\"></div>\r\n");
      out.write("            </div><br>\r\n");
      out.write("\t\t    <div class=\"row justify-content-center\">\r\n");
      out.write("            <!-- Contenedor 1-->\r\n");
      out.write("            <div class=\"col-md-0 col-lg-2 mb-0\">\r\n");
      out.write("                <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal1\" >\r\n");
      out.write("                    <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                        <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-center\" >NELSON CRIOLLO</h5>\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/icoHombre.png\" alt=\"Imagen no encontrada\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Contenedor 2-->\r\n");
      out.write("            <div class=\"col-md-0 col-lg-2 mb-0\">\r\n");
      out.write("                <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal2\">\r\n");
      out.write("                    <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                        <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-center\">EDITH FLORES</h5>\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/icoMujer.png\" alt=\"Imagen no encontrada\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Contenedor 3-->\r\n");
      out.write("            <div class=\"col-md-0 col-lg-2 mb-0\">\r\n");
      out.write("                <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal3\">\r\n");
      out.write("                    <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                        <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-center\">ALFREDO SOTO</h5>\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/icoHombre.png\" alt=\"Imagen no encontrada\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Contenedor 4-->\r\n");
      out.write("            <div class=\"col-md-0 col-lg-2 mb-0\">\r\n");
      out.write("                <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal4\">\r\n");
      out.write("                    <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                        <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-center\">FRANCO CHAVEZ</h5>\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/icoHombre.png\" alt=\"Imagen no encontrada\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <!-- Contenedor 5-->\r\n");
      out.write("            <div class=\"col-md-0 col-lg-2 mb-0\">\r\n");
      out.write("                <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal5\">\r\n");
      out.write("                    <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                        <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-center\">JORGE CHAVEZ</h5>\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/icoHombre.png\" alt=\"Imagen no encontrada\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("             <!-- Contenedor 6-->\r\n");
      out.write("            <div class=\"col-md-0 col-lg-2 mb-0\">\r\n");
      out.write("                <div class=\"portfolio-item mx-auto\" data-bs-toggle=\"modal\" data-bs-target=\"#portfolioModal6\">\r\n");
      out.write("                    <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                        <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-plus fa-3x\"></i></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <h5 class=\"text-center\">EDUARDO ROJAS</h5>\r\n");
      out.write("                    <img class=\"img-fluid\" src=\"img/icoHombre.png\" alt=\"Imagen no encontrada\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("    \t\t</section>\r\n");
      out.write("           <!-- Portfolio Modal 1--> \r\n");
      out.write("         <div class=\"portfolio-modal modal fade\" id=\"portfolioModal1\" tabindex=\"-1\" aria-labelledby=\"portfolioModal1\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-x\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Nelson Criollo</h2>\r\n");
      out.write("                                <!-- Icon Divider-->\r\n");
      out.write("                                <div class=\"divider-custom\">\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                <p class=\"mb-4\"> Mi nombre es Nelson Criollo y actualmente me encuentro cursando el cuarto ciclo de la carrera de \"Computación e Informática\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ten el instituto Cibertec. Mi hobbie es la tecnología y programación. Una de mis metas es ser un gran programador y poder \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdesempeñarme en diferentes campos de la tecnología aplicando los conocimientos obtenido durantes todos mis años de estudio. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Portfolio Modal 2-->\r\n");
      out.write("    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal2\" tabindex=\"-1\" aria-labelledby=\"portfolioModal2\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-x\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Edith Flores</h2>\r\n");
      out.write("                                <!-- Icon Divider-->\r\n");
      out.write("                                <div class=\"divider-custom\">\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                <p class=\"mb-4\">Mi nombre es Edith Flores y actualmente me encuentro cursando el cuarto ciclo de la carrera de \"Computación e Informática\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ten el instituto Cibertec. Mi hobbie es la programación de videojuegos. Una de mis metas es ser una gran programadora y poder \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tdesempeñarme en diferentes campos de la tecnología aplicando los conocimientos obtenido durantes todos mis años de estudio. </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Portfolio Modal 3-->\r\n");
      out.write("    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal3\" tabindex=\"-1\" aria-labelledby=\"portfolioModal3\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-x\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Alfredo Soto</h2>\r\n");
      out.write("                                <!-- Icon Divider-->\r\n");
      out.write("                                <div class=\"divider-custom\">\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                <p class=\"mb-4\">Mucho gusto mi nombre es Alfredo Soto actualmente me encuentro cursando el cuarto ciclo de la carrera de Computación e Informática en el prestigioso\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tinstituto Cibertec hace muchos años tuve también el placer de haber cursado la carrera de Periodismo en la Universidad Jaime Bausate y Meza y a pesar de\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tno haber podido terminar dicha carrera me siento muy identificado con las letras; soy un gran amante de la lectura, del deporte, la música, el cine e incluso\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tlos videojuegos. \"De todo un poco\" es una frase que sintetiza muy bien mi personalidad.</p>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Portfolio Modal 4-->\r\n");
      out.write("    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal4\" tabindex=\"-1\" aria-labelledby=\"portfolioModal4\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-x\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Franco Chavez</h2>\r\n");
      out.write("                                <!-- Icon Divider-->\r\n");
      out.write("                                <div class=\"divider-custom\">\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                <p class=\"mb-4\">Me llamo Franco Chávez y soy estudiante del instituto Cibertec de la carrera de Computación e Informática, cursando actualmente el cuarto ciclo. \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tEn mis ratos libres me gusta jugar fútbol y cantar. Mi meta principal es poder terminar mi carrera y desempeñarme de la mejor manera \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ten el puesto que me asignen. </p>\r\n");
      out.write("                                \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <!-- Portfolio Modal 5-->\r\n");
      out.write("    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal5\" tabindex=\"-1\" aria-labelledby=\"portfolioModal5\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-x\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Jorge Chavez</h2>\r\n");
      out.write("                                <!-- Icon Divider-->\r\n");
      out.write("                                <div class=\"divider-custom\">\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                <p class=\"mb-4\"> Me llamo Jorge Chávez y soy estudiante del instituto Cibertec de la carrera de Computación e Informática, cursando actualmente el cuarto ciclo. \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tEn mis ratos libres me gusta jugar fútbol y hacer música. Mi meta principal es poder terminar mi carrera y desempeñarme de la mejor manera \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ten el puesto que me asignen.</p>\r\n");
      out.write("                               \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <!-- Portfolio Modal 6-->\r\n");
      out.write("    <div class=\"portfolio-modal modal fade\" id=\"portfolioModal6\" tabindex=\"-1\" aria-labelledby=\"portfolioModal6\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog modal-x\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header border-0\"><button class=\"btn-close\" type=\"button\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button></div>\r\n");
      out.write("                <div class=\"modal-body text-center pb-5\">\r\n");
      out.write("                    <div class=\"container\">\r\n");
      out.write("                        <div class=\"row justify-content-center\">\r\n");
      out.write("                            <div class=\"col-lg-8\">\r\n");
      out.write("                                <!-- Portfolio Modal - Title-->\r\n");
      out.write("                                <h2 class=\"portfolio-modal-title text-secondary text-uppercase mb-0\">Eduardo Rojas</h2>\r\n");
      out.write("                                <!-- Icon Divider-->\r\n");
      out.write("                                <div class=\"divider-custom\">\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                               \r\n");
      out.write("                                <!-- Portfolio Modal - Text-->\r\n");
      out.write("                                <p class=\"mb-4\">Me llamo Eduardo Rojas y soy estudiante de cuarto ciclo de la carrera de Computación e Informática en el instituto Cibertec.\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\tEn mis ratos libres me gusta escuchar música. Mi meta principal es poder terminar mi carrera y aplicar mis conocimientos en programación adquiridos\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\ta lo largo de todos estos años. </p>\r\n");
      out.write("                               \r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t    <!-- Mision -->\r\n");
      out.write("\t\t\t<div class=\"row justify-content-center\" >\r\n");
      out.write("\t\t\t  <div class=\"card mb-5\" style=\"max-width: 1000px;\">\r\n");
      out.write("\t\t\t  <div class=\"row g-0\">\r\n");
      out.write("\t\t\t    <div class=\"col-md-4\">\r\n");
      out.write("\t\t\t      <img src=\"img/mision.png\" class=\"img-fluid rounded-start\" alt=\"...\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"col-md-8\">\r\n");
      out.write("\t\t\t      <div class=\"card-body\" >\r\n");
      out.write("\t\t\t        <h5 class=\"card-title\">Mision</h5>\r\n");
      out.write("\t\t\t        <p class=\"card-text\">\"Somos un organismo autónomo del Estado cuyos objetivos principales son la defensa de la legalidad, \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tde los derechos ciudadanos y de los intereses públicos; la representación de la sociedad en juicio, para los efectos \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tde defender a la familia, a los menores e incapaces y el interés social, así como para velar por la moral pública; \r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tla persecución del delito y la reparación civil.\".</p>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t      \r\n");
      out.write("\t\t\t        </div>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t</div>\t\r\n");
      out.write("\t\t <!-- Vision -->\r\n");
      out.write("\t\t<div class=\"row justify-content-center\">\r\n");
      out.write("\t\t  <div class=\"card mb-5\" style=\"max-width: 1000px;\">\r\n");
      out.write("\t\t\t <div class=\"row g-0\">\r\n");
      out.write("\t\t\t    <div class=\"col-md-4\">\r\n");
      out.write("\t\t\t      <img src=\"img/vision.png\" class=\"img-fluid rounded-start\" alt=\"...\">\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  <div class=\"col-md-8\">\r\n");
      out.write("\t\t\t      <div class=\"card-body\">\r\n");
      out.write("\t\t\t        <h5 class=\"card-title\">Vision</h5>\r\n");
      out.write("\t\t\t        <p class=\"card-text\">\"Nuestra visión es convertirnos en el ente fiscalizador por excelencia previniendo el delito en todas sus formas\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tciñendonos siempre dentro de los márgenes de la ley y actuando de oficio a instancia de la parte agraviada o por acción\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tpopular, si se trata de un delito de comisión inmediata.\"</p>\r\n");
      out.write("\t\t\t        \r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t       </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t   </div>\r\n");
      out.write("\t\t</div>\t\t\t\t\r\n");
      out.write("\t\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\" integrity=\"sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- JS para validación-->\r\n");
      out.write("<script src=\"https://cdn.bootcdn.net/ajax/libs/bootstrap-validator/0.4.0/js/bootstrapValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\tvar popoverTriggerList = [].slice.call(document\r\n");
      out.write("\t\t\t\t.querySelectorAll('[data-bs-toggle=\"popover\"]'))\r\n");
      out.write("\t\tvar popoverList = popoverTriggerList.map(function(popoverTriggerEl) {\r\n");
      out.write("\t\t\treturn new bootstrap.Popover(popoverTriggerEl)\r\n");
      out.write("\t\t})\r\n");
      out.write("\t</script>\r\n");
      out.write("<script>\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
